spring:
  application:
    name: OAuth2JWT
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_client?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: QAYuHZgruVgWRc5ckcqa
            client-secret: FE_ghqCjkh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 529951311508-0o43mh4b8pn3204bto9r2h4g57perui2.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          #자체 인가,리소스서버
          seung:
            client-name: seung
            provider: seung
            client-id: 5ca90af7-ccd3-4d8a-80e9-b514d540c980
            client-secret: secret
            redirect-uri: http://localhost:8080/login/oauth2/code/seung
            authorization-grant-type: authorization_code
            scope: profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          #자체 인가,리소스서버
          seung:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9001/me
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-name-attribute: response
